/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppTopbar: typeof import('./../components/AppTopbar.vue')['default']
    BubbleCard: typeof import('./../components/theme/BubbleCard.vue')['default']
    BubbleGrid: typeof import('./../components/theme/BubbleGrid.vue')['default']
    BubblePreview: typeof import('./../components/theme/BubblePreview.vue')['default']
    BubbleSettingsModal: typeof import('./../components/theme/BubbleSettingsModal.vue')['default']
    ThemeCard: typeof import('./../components/theme/ThemeCard.vue')['default']
    ThemeList: typeof import('./../components/theme/ThemeList.vue')['default']
  }
}
